// <auto-generated />
namespace B_KOM_Sklep_internetowy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class opn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(opn));
        
        string IMigrationMetadata.Id
        {
            get { return "202009281059446_opn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
