// <auto-generated />
namespace B_KOM_Sklep_internetowy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editedPromotionv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedPromotionv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202009250858338_editedPromotionv1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
